# Generated by Django 3.2.3 on 2021-05-21 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 16, 51, 35, 699165)),
        ),
        migrations.AlterField(
            model_name='stories',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 16, 51, 35, 699165)),
        ),
    ]
