# Generated by Django 3.2.3 on 2021-05-21 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210521_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stories',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
